version: "3.8"
services:

  redis_insighter:
    image: redis
    ports:
      - "7085:7085"
    restart: always
    volumes:
      - redis_insighter_volume:/DB/Redis/insighter/data/db
    command: ["redis-server", "--port", "7085"]
    networks:
      - stage_network

  insighter_bot:
    image: docker.io/artemprod/insighter_bot:${IMAGE_TAG:-latest}
    volumes:
      - shared_volume:/var/lib/telegram-bot-api
    depends_on:
      - mongo_insight
      - redis_insighter
      - telegram_bot_server
    restart: always
    env_file:
      - .env
    networks:
      - stage_network

volumes:
  redis_insighter_volume:
  shared_volume:

networks:
  stage_network:
    external: true