name: Insighter Deploy Workflow
on: workflow_dispatch
jobs:
  #Название работы 
  build_docker:
    #На какрой платформе будет запуск
    runs-on: ubuntu-latest
    #Шаг джобы
    steps:
      - name: Print to console 
        #Команда для операционной системы которую надо выполнить 
        run: echo Hello Actions
      - name: Print a few lines
        run: |
          echo first line
          echo second line
    
    
    
